name: sample-dockerfile
services:
- name: sample-dockerfile
  source_dir: frontend
  dockerfile_path: frontend/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: sciabarrado/sample-dockerfile
  